### ISSUE TITLE
mitm.it does not install CA

### ISSUE THREAD

**Issue by ankushagarwal** [thebradbain/snapception#1]
I can't get this to work on my iPhone. When I visit mitm.it from my phone, or any other device, it redirects me to grit.io. How do I install the CA. I have the proxy up and running on my Macbook pro.

**Comment by thebradbain** [comment]
Did you connect to the proxy on your device before visiting mitm.it on it?

**Comment by ankushagarwal** [comment]
I did not. Sorry about that.

I could install the certificate, and I set the proxy correctly and I see a ton of requests going through the proxy, but I don't see any snaps being captured by the proxy. I sent a couple of snaps after being connected to the proxy.

**Comment by thebradbain** [comment]
Hm, did you actually refresh your snapchat list? A notification isn't enough, as Snapchat does not actually receive the encrypted snap until you open the app.

**Comment by ankushagarwal** [comment]
Oh, I did not receive a snap. I just sent one. Let me try receiving one.

**Comment by ankushagarwal** [comment]
Received a snap. Works perfectly!
