### ISSUE TITLE
Video Snapchats?

### ISSUE THREAD

**Issue by ridhoq** [thebradbain/snapception#5]
This program doesn't seem to allow me to view video snapchats that I receive. I don't know much about the video encoding that Snapchat uses though, so I'm not sure if it is actually feasible.

**Comment by thebradbain** [comment]
You're right — Snapception isn't able to decrypt videos at this time. It is possible however, and I think videos and images use the same key for encryption but different encodings. I'll investigate into adding it in the future, but if you come up with a solution feel free to contribute!

**Comment by TRManderson** [comment]
On browsing some other Snapchat decryption projects, it seems like the encryption used is identical between pictures and videos, so there should be no need to change the decryption code for this at all.
